"""
Django settings for ihatetobudget project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
import sys
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError("Missing required environment variable: DJANGO_SECRET_KEY")


# SECURITY WARNING: don't run with debug turned on in production!
# For deployment checks, ensure this env var is set to "False".
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# When running the test suite, Django's test client uses plain HTTP.
# Redirecting to HTTPS would introduce unexpected 301s in tests.
# True when Django's test runner is executing.
IS_TEST = (os.environ.get("PYTEST_CURRENT_TEST") is not None) or ("test" in sys.argv[0])



# --- Deployment hardening (Django security.W004/W008/W012/W016) ---
# These should be enabled when the site is served behind HTTPS (e.g. via Caddy).
SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "31536000"))

# Avoid HTTPS redirects during the test suite.
# NOTE: docker-compose.env may not always propagate into the running container.
# Use a safe default but allow overriding with DJANGO_SECURE_SSL_REDIRECT.
SECURE_SSL_REDIRECT = (
    os.environ.get("DJANGO_SECURE_SSL_REDIRECT", "False") == "True"
) and (not IS_TEST)




SESSION_COOKIE_SECURE = os.environ.get("DJANGO_SESSION_COOKIE_SECURE", "True") == "True"

CSRF_COOKIE_SECURE = os.environ.get("DJANGO_CSRF_COOKIE_SECURE", "True") == "True"
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", "True") == "True"
SECURE_HSTS_PRELOAD = os.environ.get("DJANGO_SECURE_HSTS_PRELOAD", "True") == "True"


ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")



# Application definition

INSTALLED_APPS = [
    "django_crontab",
    # "mathfilters" is optional in some environments.
    # It's used only for template filters; if it's not installed, we can
    # still run the app's core tests.
    
    

    "colorfield",

    # bootstrap4 is only needed for template tag libraries (used in base.html).
    "bootstrap4",


    "sheets.apps.SheetsConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ihatetobudget.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, pkg, "template")
            for pkg in ["ihatetobudget", "sheets"]
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "libraries": {
                #  Make `ihatetobudget_extras` available to other apps
                "ihatetobudget_extras": "ihatetobudget.templatetags.ihatetobudget_extras",  # noqa: E501
            },
            "context_processors": [
                "ihatetobudget.template.context_processors.version",
                "sheets.template.context_processors.sheet_date_list",
                "sheets.template.context_processors.current_sheet_date",
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ihatetobudget.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Auth

LOGIN_REDIRECT_URL = "/sheets/"
LOGOUT_REDIRECT_URL = "/"


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",  # noqa: E501
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = "/static/"


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Currency formatting


CURRENCY_GROUP_SEPARATOR = os.environ.get("CURRENCY_GROUP_SEPARATOR", " ")
CURRENCY_DECIMAL_SEPARATOR = os.environ.get("CURRENCY_DECIMAL_SEPARATOR", ",")
CURRENCY_PREFIX = os.environ.get("CURRENCY_PREFIX", "")
CURRENCY_SUFFIX = os.environ.get("CURRENCY_SUFFIX", " €")


# Cron

CRONJOBS = [
    # At 00:05 on day-of-month 1.
    # Thanks https://crontab.guru/#5_0_1_*_*
    ("5 0 1 * *", "sheets.cron.recurring_expenses")
]


# Media (for receipt uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

